#!/usr/bin/env python3
"""
Gemini AI Council Distribution Optimizer
Analyzes village patterns and suggests optimal payout strategies
"""
import sqlite3
import json
from datetime import datetime
from pathlib import Path

print("🏛️ GEMINI COUNCIL DISTRIBUTION OPTIMIZER")
print("=" * 60)

# Connect to databases
conn = sqlite3.connect('instance/imperial.db')
cursor = conn.cursor()

# Get council data with village mapping
cursor.execute('''
    SELECT 
        member_id, 
        phone_suffix, 
        allocation,
        CASE 
            WHEN member_id LIKE 'THO%' THEN 'Thohoyandou'
            WHEN member_id LIKE 'SIB%' THEN 'Sibasa'
            WHEN member_id LIKE 'MAL%' THEN 'Malamulele'
            WHEN member_id LIKE 'LWM%' THEN 'Lwamondo'
            WHEN member_id LIKE 'MAN%' THEN 'Manini'
            ELSE 'Other'
        END as village
    FROM council_pins
    ORDER BY village, member_id
''')
council_members = cursor.fetchall()

# Get village language data
cursor.execute('''
    SELECT village, COUNT(*) FROM user
    WHERE village IS NOT NULL AND village != ""
    GROUP BY village ORDER BY COUNT(*) DESC
''')
village_stats = cursor.fetchall()

print(f"📊 Analyzing {len(council_members)} council members across multiple villages")
print(f"🌍 Village distribution loaded for {len(village_stats)} communities")

# Calculate distribution scenarios
base_total = sum(m[2] for m in council_members)
alpha_total = base_total * 1.25
alpha_boost = alpha_total - base_total

print(f"\n💰 FINANCIAL ANALYSIS:")
print(f"   Base Fund: R{base_total:,.2f}")
print(f"   Alpha Boost (1.25x): R{alpha_boost:,.2f}")
print(f"   Total with Alpha: R{alpha_total:,.2f}")

# Group by village for language-appropriate distribution
villages = {}
for member in council_members:
    village = member[3]
    if village not in villages:
        villages[village] = {'count': 0, 'total': 0, 'members': []}
    villages[village]['count'] += 1
    villages[village]['total'] += member[2]
    villages[village]['members'].append(member)

print(f"\n🏘️ VILLAGE DISTRIBUTION:")
for village, data in villages.items():
    lang = "Tshivenda" if village in ['Thohoyandou', 'Sibasa', 'Lwamondo', 'Manini'] else "Xitsonga" if village in ['Malamulele'] else "English"
    flag = "🏔️" if lang == "Tshivenda" else "🌊" if lang == "Xitsonga" else "🇬🇧"
    print(f"   {flag} {village}: {data['count']} members | R{data['total']:,.2f} | {lang}")

# Save analysis
analysis = {
    'timestamp': datetime.now().isoformat(),
    'base_fund': base_total,
    'alpha_boost': alpha_boost,
    'total_distribution': alpha_total,
    'villages': villages,
    'village_stats': village_stats,
    'recommendations': {
        'payout_timing': 'Peak liquidity window: Next 72 hours',
        'priority_order': ['Thohoyandou', 'Malamulele', 'Sibasa', 'Lwamondo', 'Manini'],
        'language_templates': {
            'Tshivenda': 'U wana R{amount} u bva kha Imperial Network',
            'Xitsonga': 'U kume R{amount} ku suka eka Imperial Network',
            'English': 'You received R{amount} from Imperial Network'
        },
        'risk_level': 'Low - Stable corridor',
        'gauteng_impact': f'Will inject R{alpha_total:,.2f} into local economy'
    }
}

with open('council_ai_analysis.json', 'w') as f:
    json.dump(analysis, f, indent=2, default=str)

print(f"\n✅ Analysis saved to council_ai_analysis.json")

# Create distribution script (using simple string concatenation to avoid f-string issues)
script_content = """#!/bin/bash
# 🏛️ COUNCIL ALPHA DISTRIBUTION SCRIPT
# Generated by Gemini AI - """ + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + """

echo "🏛️ IMPERIAL COUNCIL ALPHA DISTRIBUTION"
echo "========================================"
echo "Total Fund: R""" + f"{base_total:,.2f}" + """
echo "Alpha Boost: R""" + f"{alpha_boost:,.2f}" + """
echo "Final Distribution: R""" + f"{alpha_total:,.2f}" + """
echo ""
"""

# Add village breakdown
script_content += 'echo "📊 Distribution by Village:"\n'
for village, data in villages.items():
    script_content += f'echo "   {village}: {data["count"]} members | R{int(data["total"]*1.25):,} (with Alpha)"\n'

script_content += """
echo ""
echo "🚀 To execute distribution, run:"
echo "   sqlite3 instance/imperial.db \\"
echo '     "UPDATE council_pins SET status=\\'"'"'distributed\\'"'"' WHERE status=\\'"'"'active\\'"'"';"'
echo ""
echo "💬 Language Templates Ready:"
echo "   🏔️ Tshivenda: U wana R{amount} u bva kha Imperial Network"
echo "   🌊 Xitsonga:  U kume R{amount} ku suka eka Imperial Network"
echo "   🇬🇧 English:   You received R{amount} from Imperial Network"
"""

with open('distribute_council_alpha.sh', 'w') as f:
    f.write(script_content)

# Create notification templates
import os
os.makedirs('notifications', exist_ok=True)

templates = [
    ('ve', 'U wana R{amount} u bva kha Imperial Network'),
    ('ts', 'U kume R{amount} ku suka eka Imperial Network'),
    ('en', 'You received R{amount} from Imperial Network')
]

for lang, template in templates:
    with open(f'notifications/council_{lang}.txt', 'w') as nf:
        nf.write(template)

# Make the script executable
os.chmod('distribute_council_alpha.sh', 0o755)

print("\n✅ Distribution scripts generated")
print("📁 Location: distribute_council_alpha.sh")
print("📁 Templates: notifications/council_*.txt")

conn.close()
